"""Generate ``web/src/types.ts`` from the pydantic row model.

    python -m pipeline.emit_types            # write the file
    python -m pipeline.emit_types --check    # fail if it is out of date

The row schema was maintained by hand in two languages, and they had already
drifted: ``also_listed_as`` was added to ``schema.Stock`` and shipped in
stocks.json, while the TypeScript interface never learned about it, so the
frontend was typed against a dataset the pipeline no longer produced. Pydantic
already knows every field and its type, so the TypeScript is generated from it
and the drift cannot come back.

``--check`` runs in the test suite, which is what makes this binding rather than
merely available.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Literal, get_args, get_origin

from . import config as C
from .schema import Stock

TYPES_TS = C.ROOT / "web" / "src" / "types.ts"

HEADER = """// Generated by `python -m pipeline.emit_types` from pipeline/schema.py.
// Do not edit by hand: the pipeline's pydantic model is the source of truth,
// and `pytest tests/test_types.py` fails if this file drifts from it.
"""

# The hand-written tail of types.ts: shapes that belong to the frontend rather
# than to a dataset row, so they are not generated.
FOOTER = """
export interface Meta {
  generated_at: string
  count: number
  universe_source: string
  price_source: string
  fundamentals_sources: string[]
  fundamentals_breakdown: Record<string, number>
  stale_rows: number
  fx_rates: Record<string, number>
  coverage: Record<string, number>
}

export type Sparklines = Record<string, number[]>
"""


def _ts_type(annotation) -> str:
    """Render one pydantic field annotation as a TypeScript type."""
    origin = get_origin(annotation)
    if origin is Literal:
        return " | ".join(f"'{a}'" for a in get_args(annotation))
    if origin is list:
        inner = get_args(annotation)[0]
        return f"{_ts_type(inner)}[]"
    args = [a for a in get_args(annotation)]
    if args:                                         # Optional[X] is Union[X, None]
        nullable = type(None) in args
        rest = [a for a in args if a is not type(None)]
        rendered = " | ".join(_ts_type(a) for a in rest)
        return f"{rendered} | null" if nullable else rendered
    return {str: "string", int: "number", float: "number", bool: "boolean"}.get(
        annotation, "unknown")


def render() -> str:
    lines = [HEADER, "export interface Stock {"]
    for name, field in Stock.model_fields.items():
        lines.append(f"  {name}: {_ts_type(field.annotation)}")
    lines.append("}")
    return "\n".join(lines) + "\n" + FOOTER


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="pipeline.emit_types")
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if types.ts is out of date")
    args = parser.parse_args(argv)

    wanted = render()
    current = TYPES_TS.read_text(encoding="utf-8") if TYPES_TS.exists() else ""
    if args.check:
        if current != wanted:
            print(f"{TYPES_TS} is out of date - run: python -m pipeline.emit_types",
                  file=sys.stderr)
            return 1
        return 0

    Path(TYPES_TS).write_text(wanted, encoding="utf-8")
    print(f"wrote {TYPES_TS} ({len(Stock.model_fields)} fields)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
